exports.GAMEBOARD_SIZE = 3;
exports.PLAYERS = ['X', 'O'];
exports.NULL_PLAYER = -20;
exports.NULL_PLAYER_PLACEHOLDER = " ";
exports.NULL_TURN = -10;
exports.NULL_TURN_PLACEHOLDER = " ";
exports.GAME_RESULT_UNDECIDED = -30;
exports.GAME_RESULT_DRAW = -40;
exports.GAME_WIN_SYMBOLS_CNT = 3;